### ISSUE TITLE
Incomplete tip

### ISSUE THREAD

**Issue by GirZ0n** [jetbrains-academy/kotlin-onboarding-object-oriented-programming#135]
Memory Trainer 6: the tip does not tell you how to create an empty mutable list

![image](https://github.com/jetbrains-academy/kotlin-onboarding-object-oriented-programming/assets/55441714/a463611b-0a46-4034-9c59-8ceed336845d)

**Comment by nbirillo** [comment]
It's already in the main branch, and the new version of the course will be released on the Marketplace after fixing [this](https://youtrack.jetbrains.com/issue/EDU-5979/Duplicated-folders-at-course-update) issue
