### ISSUE TITLE
Wrong class is reported as required data class in Memory Trainer Project

### ISSUE THREAD

**Issue by VeMike** [jetbrains-academy/kotlin-onboarding-object-oriented-programming#168]
The _Memory Trainer Project_ (Part 6) requires the user to implement a `Stat` class. This `Stat` class needs to be a `data class Stat`. However, if I make it a `class Stat` the error after hitting _Check_ says: _The **StatService** should be a data class!_. But it is the `Stat` that should be a `data class`. Not the `StatService`.

I fixed it here https://github.com/VeMike/kotlin-onboarding-object-oriented-programming/commit/c1d1d349f9886bfdd35146e9c29a35371658aaa8 and can do a PR for it.

**Comment by nbirillo** [comment]
@VeMike thank you a lot!
